public class PalindromeChecker {
    public boolean isPalindrome(String s) {
        // Regex generated by copilot since I suck at it :(
        String rawText = s.replaceAll("[^a-zA-Z0-9]", "").toLowerCase();
        System.out.println(rawText);
        return rawText.contentEquals(new StringBuilder(rawText).reverse());
    }
}